services:
  nginx:
    image: nginx:1.27
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  api:
    build: .
    env_file: .env
    environment:
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "PYTHONPATH=/app alembic upgrade head &&
             gunicorn -c gunicorn.conf.py app.main:app"
    restart: unless-stopped

  worker:
    build: .
    env_file: .env
    environment:
      PYTHONPATH: /app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: celery -A workers.celery_app worker --loglevel=INFO
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mocktest
    ports:
      - "5433:5432"   # host 5433 → container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mocktest"]
      interval: 2s
      timeout: 2s
      retries: 15
      start_period: 5s
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6380:6379"   # host 6380 → container 6379
    restart: unless-stopped
